package com.logistics.supply.util;

import lombok.experimental.UtilityClass;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

@UtilityClass
public class LpoTemplate {

  public String LpoCompose(int lpoId, String supplier, String comment, String tableHtml) {
    String pattern = "EEEEE dd MMMMM yyyy";
    SimpleDateFormat simpleDateFormat =
            new SimpleDateFormat(pattern, new Locale("en", "UK"));

    String today = simpleDateFormat.format(new Date());
    return "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
        + "<html\n"
        + "\txmlns=\"http://www.w3.org/1999/xhtml\"\n"
        + "\txmlns:th=\"http://www.thymeleaf.org\" lang=\"en\" xml:lang=\"en\">\n"
        + "\t<head>\n"
        + "\t\t<title>LOCAL ORDER REQUISITION</title>\n"
        + "\t\t<meta name=\"x-apple-disable-message-reformatting\" />\n"
        + "\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
        + "\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n"
        + "\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
        + "\t\t<meta name=\"x-apple-disable-message-reformatting\" />\n"
        + "\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
        + "\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n"
        + "\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
        + "\t\t<base href=\"https://preview.hs-sites.com\" target=\"_blank\" />\n"
        + "\t\t<meta name=\"generator\" content=\"HubSpot\" />\n"
        + "\t\t<meta property=\"og:url\" content=\"http://oze-4216469.hs-sites.com/your-digital-receipt-from-tozé-business-app?hs_preview=URDbBNaP-36188940965\" />\n"
        + "\t\t<meta name=\"robots\" content=\"noindex,follow\" />\n"
        + "\t\t<style>@font-face {\n"
        + "font-family: 'Lato'; font-style: italic; font-weight: 400; src: local('Lato Italic'), local('Lato-Italic'), url('https://fonts.gstatic.com/s/lato/v17/S6u8w4BMUTPHjxsAXC-v.ttf') format('truetype');\n"
        + "}\n"
        + "@font-face {\n"
        + "font-family: 'Lato'; font-style: italic; font-weight: 700; src: local('Lato Bold Italic'), local('Lato-BoldItalic'), url('https://fonts.gstatic.com/s/lato/v17/S6u_w4BMUTPHjxsI5wq_Gwfo.ttf') format('truetype');\n"
        + "}\n"
        + "@font-face {\n"
        + "font-family: 'Lato'; font-style: normal; font-weight: 400; src: local('Lato Regular'), local('Lato-Regular'), url('https://fonts.gstatic.com/s/lato/v17/S6uyw4BMUTPHjx4wWw.ttf') format('truetype');\n"
        + "}\n"
        + "@font-face {\n"
        + "font-family: 'Lato'; font-style: normal; font-weight: 700; src: local('Lato Bold'), local('Lato-Bold'), url('https://fonts.gstatic.com/s/lato/v17/S6u9w4BMUTPHh6UVSwiPHA.ttf') format('truetype');\n"
        + "}\n"
        + ".ExternalClass {\n"
        + "width: 100%;\n"
        + "}\n"
        + ".ExternalClass {\n"
        + "line-height: 100%;\n"
        + "}\n"
        + "body {\n"
        + "-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; -webkit-font-smoothing: antialiased; moz-osx-font-smoothing: grayscale;\n"
        + "}\n"
        + "@media only screen and (min-width:640px) {\n"
        + "  .hse-column-container {\n"
        + "    max-width: 600px !important; width: 600px !important;\n"
        + "  }\n"
        + "  .hse-column {\n"
        + "    display: table-cell; vertical-align: top;\n"
        + "  }\n"
        + "  .hse-section .hse-size-6 {\n"
        + "    max-width: 300px !important; width: 300px !important;\n"
        + "  }\n"
        + "  .hse-section .hse-size-12 {\n"
        + "    max-width: 600px !important; width: 600px !important;\n"
        + "  }\n"
        + "}\n"
        + "@media only screen and (max-width:639px) {\n"
        + "  img.stretch-on-mobile {\n"
        + "    height: auto !important; width: 100% !important;\n"
        + "  }\n"
        + "  .hs_rss_email_entries_table img {\n"
        + "    height: auto !important; width: 100% !important;\n"
        + "  }\n"
        + "  .display_block_on_small_screens {\n"
        + "    display: block;\n"
        + "  }\n"
        + "  .hs_padded {\n"
        + "    padding-left: 20px !important; padding-right: 20px !important;\n"
        + "  }\n"
        + "}\n"
        + "\n"
        + ".styled-table {\n"
        + "        border-collapse: collapse;\n"
        + "        margin: 25px 0;\n"
        + "        font-size: 0.95em;\n"
        + "        font-family: HelveticaNeue-Light;\n"
        + "        min-width: 400px;\n"
        + "        \n"
        + "      }\n"
        + "\n"
        + "      .styled-table thead tr {\n"
        + "        background-color: #009879;\n"
        + "        color: #ffffff;\n"
        + "        text-align: left;\n"
        + "      }\n"
        + "\n"
        + "      .styled-table tbody tr {\n"
        + "        border-bottom: 1px solid #dddddd;\n"
        + "      }\n"
        + "\n"
        + "      .styled-table tbody tr:nth-of-type(even) {\n"
        + "        background-color: #f3f3f3;\n"
        + "      }\n"
        + "\n"
        + "      .styled-table tbody tr:last-of-type {\n"
        + "        border-bottom: 2px solid #0075c9;\n"
        + "      }\n"
        + "\n"
        + "      .styled-table th,\n"
        + "      .styled-table td {\n"
        + "        padding: 12px 20px;\n"
        + "      }\n"
        + "\n"
        + "</style>\n"
        + "\t</head>\n"
        + "\t<body bgcolor=\"#EAF0F6\" style=\"font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #0075c9; word-break: break-word; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; -webkit-font-smoothing: antialiased; moz-osx-font-smoothing: grayscale; margin: 0; padding: 0;\">\n"
        + "\t\t<div style=\"display: none !important; font-size: 1px; color: #EAF0F6; line-height: 1px; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;\">LPO</div>\n"
        + "\t\t<div class=\"hse-body-background\" style=\"background-color: #eaf0f6;\" bgcolor=\"#0075c9\">\n"
        + "\t\t\t<table role=\"presentation\" class=\"hse-body-wrapper-table\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100% !important; min-width: 320px !important; height: 100% !important; margin: 0; padding: 0;\" width=\"100%\" height=\"100%\">\n"
        + "\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t<td class=\"hse-body-wrapper-td\" valign=\"top\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding-top: 20px; \">\n"
        + "\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_email_flex_area\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"email_flex_area\">\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-section hse-section-first\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; padding-bottom: 0px; padding-top: 0px; background: #0075c9 url('https://f.hubspotusercontent10.net/hubfs/4216469/gradiaent%20blue.jpg') no-repeat center / 100% 100%;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-12\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<table class=\"hse-image-wrapper\" role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0075c9;\" >\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\" valign=\"top\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; color: #0075c9; word-break: break-word; font-size: 0px; padding: 0px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img alt=\"LPO\" src=\"https://www.blueskies.com/wp-content/uploads/2017/10/retina-01.png\" style=\"outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; max-width: 100%; font-size: 16px;\" width=\"100\" align=\"middle\" />\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; background-color: #ffffff;\" bgcolor=\"#ffffff\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-12\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"rich_text\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style=\"mso-line-height-rule: exactly; line-height: 175%; margin: 0;\" align=\"center\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<strong>LOCAL PURCHASE ORDER</strong>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; background-color: #ffffff;\" bgcolor=\"#ffffff\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-6\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 10px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"rich_text\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style=\"mso-line-height-rule: exactly; line-height: 175%; margin: 0;\">LPO ID: </p>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-6\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 10px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"rich_text\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style=\"mso-line-height-rule: exactly; line-height: 175%; margin: 0;\" align=\"right\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span th:text=\"${subscriptionPlan}\" />"
        + lpoId
        + "\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; background-color: #ffffff;\" bgcolor=\"#ffffff\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-12\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 0px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" width=\"100%\" align=\"center\" border=\"0\" style=\"position: relative; top: -1px; min-width: 20px; width: 100%; max-width: 100%; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; font-size: 1px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"100%\" valign=\"middle\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; line-height: 0; border-bottom-style: solid; mso-border-bottom-alt: 1px solid #EEEEEE; border-bottom-width: 1px; border-color: transparent transparent #eeeeee;\"></td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; background-color: #ffffff;\" bgcolor=\"#ffffff\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-6\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 10px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"rich_text\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style=\"mso-line-height-rule: exactly; line-height: 175%; margin: 0;\">Supplier: </p>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-6\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 10px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"rich_text\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style=\"mso-line-height-rule: exactly; line-height: 175%; margin: 0;\" align=\"right\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span th:text=\"${receiptNumber}\" />"
        + supplier
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; background-color: #ffffff;\" bgcolor=\"#ffffff\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-12\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 0px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" width=\"100%\" align=\"center\" border=\"0\" style=\"position: relative; top: -1px; min-width: 20px; width: 100%; max-width: 100%; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; font-size: 1px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"100%\" valign=\"middle\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; line-height: 0; border-bottom-style: solid; mso-border-bottom-alt: 1px solid #EEEEEE; border-bottom-width: 1px; border-color: transparent transparent #eeeeee;\"></td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; background-color: #ffffff;\" bgcolor=\"#ffffff\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-6\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 10px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"rich_text\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style=\"mso-line-height-rule: exactly; line-height: 175%; margin: 0;\">Date:</p>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-6\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 10px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"rich_text\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style=\"mso-line-height-rule: exactly; line-height: 175%; margin: 0;\" align=\"right\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span th:text=\"${trxdate}\" />"
        + today
        + "</span>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; background-color: #ffffff;\" bgcolor=\"#ffffff\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-12\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 0px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" width=\"100%\" align=\"center\" border=\"0\" style=\"position: relative; top: -1px; min-width: 20px; width: 100%; max-width: 100%; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; font-size: 1px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"100%\" valign=\"middle\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; line-height: 0; border-bottom-style: solid; mso-border-bottom-alt: 1px solid #EEEEEE; border-bottom-width: 1px; border-color: transparent transparent #eeeeee;\"></td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; background-color: #ffffff;\" bgcolor=\"#ffffff\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-6\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 10px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"rich_text\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p style=\"mso-line-height-rule: exactly; line-height: 175%; margin: 0;\">Comment:</p>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-6\"></div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; background-color: #ffffff;\" bgcolor=\"#ffffff\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-12\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 0px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" width=\"100%\" align=\"center\" border=\"0\" style=\"position: relative; top: -1px; min-width: 20px; width: 100%; max-width: 100%; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; font-size: 1px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"100%\" valign=\"middle\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; line-height: 0; border-bottom-style: solid; mso-border-bottom-alt: 1px solid #EEEEEE; border-bottom-width: 1px; border-color: transparent transparent #eeeeee;\"></td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; background-color: #ffffff;\" bgcolor=\"#ffffff\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-12\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 0px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" width=\"100%\" align=\"center\" border=\"0\" style=\"position: relative; top: -1px; min-width: 20px; width: 100%; max-width: 100%; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-collapse: collapse; font-size: 1px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"100%\" valign=\"middle\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; line-height: 0; border-bottom-style: solid; mso-border-bottom-alt: 1px solid #EEEEEE; border-bottom-width: 1px; border-color: transparent transparent #eeeeee;\"></td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t<!-- <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"><tbody><tr><td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 40px 20px 10px;\"><div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\"><div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_rich_text\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"rich_text\"><p style=\"mso-line-height-rule: exactly; line-height: 175%; margin: 0;\" align=\"center\">Questions about your receipt?</p><p style=\"mso-line-height-rule: exactly; line-height: 175%; margin: 0;\" align=\"center\"><a href=\"https://wa.me/233545750476\" rel=\"noopener\" style=\"mso-line-height-rule: exactly; color: #00a4bd; text-decoration: underline;\" data-hs-link-id=\"0\" target=\"_blank\">Contact Coach</a></p></div></div></td></tr></tbody></table> -->\n"
        + "\t\t\t\t\t\t\t\t\t\t<div style=\"text-align: center\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<br />\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<table\n"
        + "                                        class=\"styled-table\"\n"
        + "                                        style=\"background-color: #fafafa\"\n"
        + "                                        align=\"center\"\n"
        + "                                      >\n"
        + tableHtml
        + "\t\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "                                      &nbsp;\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<br />\n"
        + "                                      &nbsp;\n"
        + "                                    \n"
        + "\t\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t<div class=\"hse-section\" style=\"padding-left: 10px; padding-right: 10px;\">\n"
        + "\t\t\t\t\t\t\t\t<div class=\"hse-column-container\" style=\"min-width: 280px; max-width: 600px; width: 100%; margin-left: auto; margin-right: auto; border-collapse: collapse; border-spacing: 0; padding-bottom: 20px; padding-top: 15px;\">\n"
        + "\t\t\t\t\t\t\t\t\t<div class=\"hse-column hse-size-12\">\n"
        + "\t\t\t\t\t\t\t\t\t\t<table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-spacing: 0 !important; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t<tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"hs_padded\" style=\"border-collapse: collapse; mso-line-height-rule: exactly; font-family: Lato, Tahoma, sans-serif; font-size: 16px; color: #23496d; word-break: break-word; padding: 10px 20px;\">\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\"></div>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n"
        + "\t\t\t\t\t\t\t\t\t\t\t</tbody>\n"
        + "\t\t\t\t\t\t\t\t\t\t</table>\n"
        + "\t\t\t\t\t\t\t\t\t\t<div class=\"hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module\" style=\"color: inherit; font-size: inherit; line-height: inherit;\" data-hs-cos-general-type=\"widget\" data-hs-cos-type=\"module\"></div>\n"
        + "\t\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t\t</div>\n"
        + "\t\t\t\t\t\t</td>\n"
        + "\t\t\t\t\t</tr>\n"
        + "\t\t\t\t</tbody>\n"
        + "\t\t\t</table>\n"
        + "\t\t</div>\n"
        + "\t</body>\n"
        + "</html>\n";
  }
}
