package com.logistics.supply.enums;

public enum EmailType {
  NEW_REQUEST_MAIL,
  QUOTATION_TO_GM_AND_HOD_MAIL,
  NOTIFY_EMPLOYEE_OF_ENDORSEMENT_MAIL,
  REQUEST_ENDORSEMENT_MAIL,
  PROCUREMENT_REVIEW_MAIL,
  GENERAL_MANAGER_APPROVAL_MAIL,
  CANCEL_REQUEST_MAIL,
  NEW_USER_PASSWORD_MAIL,
  NEW_USER_CONFIRMATION_MAIL,
  STORES_GOODS_RECEIVED_EMAIL,
  SUPPLIER_QUOTATION_EMAIL,
  LPO_TO_STORES_EMAIL,
  APPROVED_REQUEST_MAIL
}
