package com.logistics.supply.enums;

import lombok.Getter;

@Getter
public enum RequestProcess {
  HOD_REQUEST_ENDORSEMENT("HOD_REQUEST_ENDORSEMENT"),
  PRICE_DETAILS_PROCUREMENT("PRICE_DETAILS_PROCUREMENT"),
  PRICE_REVIEW_HOD("PRICE_REVIEW_HOD"),
  REQUEST_APPROVAL_GM("REQUEST_APPROVAL_GM"),
  LPO_PROCUREMENT("LPO_PROCUREMENT"),
  GRN_STORES("GRN_STORES"),
  REVIEW_GRN_HOD("REVIEW_GRN_HOD"),
  REVIEW_GRN_PROCUREMENT("REVIEW_GRN_PROCUREMENT"),
  REVIEW_PAYMENT_DRAFT_GM("REVIEW_PAYMENT_DRAFT_GM"),
  REVIEW_PAYMENT_DRAFT_FM("REVIEW_PAYMENT_DRAFT_FM"),
  REVIEW_PAYMENT_DRAFT_AUDITOR("REVIEW_PAYMENT_DRAFT_AUDITOR"),
  ACCOUNT_OFFICER_RESPONSE_TO_AUDITOR_COMMENT("RESPONSE_TO_AUDITOR_COMMENT"),
  AUDITOR_RESPONSE_TO_FM_COMMENT("AUDITOR_RESPONSE_TO_FM_COMMENT"),
  REVIEW_GRN_ACCOUNTS("REVIEW_GRN_ACCOUNTS"),
  PROCUREMENT_RESPONSE_TO_ACCOUNT_GRN_COMMENT("PROCUREMENT_RESPONSE_TO_ACCOUNT_GRN_COMMENT"),
  REVIEW_FLOAT_GM("REVIEW_FLOAT_GM"),
  REVIEW_FLOAT_HOD("REVIEW_FLOAT_HOD"),
  REVIEW_PETTY_CASH_GM("REVIEW_PETTY_CASH_GM"),
  REVIEW_QUOTATION_HOD("REVIEW_QUOTATION_HOD"),
  REVIEW_QUOTATION_GM("REVIEW_QUOTATION_GM"),
  PROCUREMENT_RESPONSE_TO_QUOTATION_REVIEW("PROCUREMENT_RESPONSE_TO_QUOTATION_REVIEW"),
  REVIEW_PETTY_CASH_HOD("REVIEW_PETTY_CASH_HOD");
  String process;

  RequestProcess(String process) {
    this.process = process;
  }
}
