# Use postgres/example user/password credentials
version: '3.5'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 970b2cbf0f778be6b86acf65ad97da07862cc721fda7c7a52a73ec0cab331273
      POSTGRES_USER: omdbdzchawruik
      POSTGRES_DB: dc2fjtrn9n5cf1
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

    restart: unless-stopped

  app-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dc2fjtrn9n5cf1
      - SPRING_DATASOURCE_USERNAME=omdbdzchawruik
      - SPRING_DATASOURCE_PASSWORD=970b2cbf0f778be6b86acf65ad97da07862cc721fda7c7a52a73ec0cab331273
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SERVER_PORT=5001

networks:
  host:
    driver: bridge

volumes:
  postgres: