CREATE TABLE store (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_by INTEGER,
   created_date TIMESTAMP WITHOUT TIME ZONE,
   last_modified_by INTEGER,
   last_modified_date TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(50),
   CONSTRAINT pk_store PRIMARY KEY (id)
);