
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/bluesupply?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    #    url: ${ATARE_DB_URL}
    username: root
    password: MySimpleTruth12!@
    connection-test-query: SELECT 1
    test-while-idle: true
    test-on-borrow: true

    validation-interval: 10000
    log-validation-errors: true
    validation-query: SELECT 1



  security:
    user:
      name: user
      password: 33b2dd2f-a3e6-4d4a-ae0d-816554a5bfb1

