db:
    service:
        databaseName: postgresql://postgres:docker@localhost:5432/bluesupplydb
        password: docker
        url: jdbc:postgresql://localhost:5432/bluesupplydb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
        username: postgres
spring:
    application:
      name: supply-db-migration
    flyway:
        enabled: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

